=== rsrini7/dashboard/tools/weldmock/sample/post-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "author": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "surname": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "surname"
      ]
    },
    "body": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "tags": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ]
        },
        {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name"
          ]
        }
      ]
    },
    "title": {
      "type": "string"
    }
  },
  "required": [
    "author",
    "body",
    "id",
    "tags",
    "title"
  ]
}

=== rsrini7/dashboard/tools/weldmock/sample/post-sample.json
{
  "author": {
    "name": "seray",
    "surname": "uzgur"
  },
  "body": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero.",
  "id": 1,
  "tags": [
    {
      "id": 1,
      "name": "tech"
    },
    {
      "id": 2,
      "name": "web"
    }
  ],
  "title": "Rust Rocks!"
}
